version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: sleact
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sleact-network

  app:
    build:
      context: ./node_back/
      dockerfile: ./Dockerfile
    container_name: node_app
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - NODE_ENV=production
    ports:
      - "3095:3095"
    volumes:
      - ./node_back:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - sleact-network


networks:
  sleact-network:

volumes:
  db-data: